# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build -c Debug ./ClassLibTests/ClassLibTests.csproj

    - name: Run Tests
      run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./NewResults ./ClassLibTests/ClassLibTests.csproj

    - name: Install Report Generator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate Report
      run: reportgenerator -reports:"./NewResults/**/*.cobertura.xml" -targetdir:"./new-coverage-report" -reporttypes:"Cobertura;MarkdownSummaryGithub;HtmlSummary"

    - name: Install diff-cover
      run: pip install diff-cover

    - name: Run diff-cover
      run: diff-cover --compare-branch origin/main ./new-coverage-report/Cobertura.xml --html-report ./new-coverage-report/diff-report.html --markdown-report ./new-coverage-report/diff-report.md

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./new-coverage-report/

    - name: Write to Step Summary
      run: cat ./new-coverage-report/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
